// <auto-generated />
using System;
using Catalog.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.API.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260211140627_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Catalog.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Products_Category");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ordinateur portable haute performance avec écran 15 pouces, processeur Intel i7, 16GB RAM",
                            ImageUrl = "https://example.com/images/dell-xps-15.jpg",
                            Name = "Laptop Dell XPS 15",
                            Price = 1499.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 1, 20, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Smartphone Apple dernière génération avec puce A17 Pro, caméra 48MP",
                            ImageUrl = "https://example.com/images/iphone-15-pro.jpg",
                            Name = "iPhone 15 Pro",
                            Price = 1199.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 2, 1, 9, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Téléviseur QLED 4K 65 pouces avec HDR, Smart TV et son Dolby Atmos",
                            ImageUrl = "https://example.com/images/samsung-qled-65.jpg",
                            Name = "Samsung 65\" QLED TV",
                            Price = 1899.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 4,
                            Category = "Audio",
                            CreatedDate = new DateTime(2024, 2, 5, 11, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Casque audio sans fil avec réduction de bruit active de pointe",
                            ImageUrl = "https://example.com/images/sony-wh1000xm5.jpg",
                            Name = "Sony WH-1000XM5",
                            Price = 399.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2024, 2, 10, 16, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Tablette Apple Pro avec puce M2, écran Liquid Retina XDR, 256GB",
                            ImageUrl = "https://example.com/images/ipad-pro-12.jpg",
                            Name = "iPad Pro 12.9\"",
                            Price = 1099.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 6,
                            Category = "Accessories",
                            CreatedDate = new DateTime(2024, 2, 12, 13, 10, 0, 0, DateTimeKind.Utc),
                            Description = "Souris sans fil ergonomique pour professionnels avec 8000 DPI",
                            ImageUrl = "https://example.com/images/mx-master-3s.jpg",
                            Name = "Logitech MX Master 3S",
                            Price = 99.99m,
                            StockQuantity = 75
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
